### PR TITLE
Use IBM Plex fonts; add specification for monospace font

### PR DESCRIPTION
**Pull request by nicholas-miklaucic**
Whether or not this gets rejected for reasons of taste, there is currently no monospace font specification that I could find. This is problematic because it makes the site look different on different computers without any real control from the site itself.

This simply uses IBM Plex Sans where Open Sans or Roboto were used previously. This unifies the typographic identity of the website, and IBM Plex's comparative rarity (and bona fide open source nature) helps establish a uniform design for the site. IBM Plex Mono is the companion mono and looks excellent combined with Plex Sans: look at the git cheatsheet page for an example.

Note that I can't test that the CDN does its job, sadly, because my computer has IBM Plex already: I can verify that it tries to access that font, but I'm not sure it actually works yet. Someone who doesn't have it installed should test it.

### CODE REVIEW

**Comment by milesmcc** [comment]
I agree that the website needs a uniform typographic identity across all devices. I've tested this PR on a machine without IBM fonts installed locally, and it works perfectly!

**Comment by nicholas-miklaucic** [comment]
Good to hear. I think that's the last major issue. I'm pretty certain it only loads the fonts it uses, so there's no problem there either.

**Comment by ruddfawcett** [comment]
So we're mainly just looking at the unification of a monospace font?

**Comment by nicholas-miklaucic** [comment]
Yeah, establishing a uniform typographic identity.

**Comment by ruddfawcett** [comment]
But specifically of a monospace font, because Google's fonts will be loaded on every device just like the IBM Plex CDN will...

**Comment by nicholas-miklaucic** [comment]
Yes, but, as we've discussed previously, Open Sans and Roboto are both 1)
extremely common and therefore not particularly identifying and 2)
especially not so when used in conjunction with each other. Additionally,
not integrating a monospace font with this heightens the issue: there's not
an identifiable look of the website.

It's generally good typography to only pair fonts that you take care to
clearly separate from each other: using extremely varied weights, serif and
sans-serif together, monospace, different styles/eras, etc., or simply in
this case use a single family that is guaranteed to look consistent across
the website itself. Pairing Open Sans with a serif or something really
different like Gill Sans would work, but I think in this case it clashes
with Roboto. Additionally, as I touched upon earlier, Roboto and Open Sans
are an extremly common combination that do little to separate a site. (Most
combinations of it use weights to distinguish them very clearly, which
would be an acceptable solution as well although monospace is still an
issue: http://www.axelwyart.com/cop21/ is a good example of this.)

**Pull request merged**
