### PR TITLE
fix typo in assignments

### PR DESCRIPTION
**Pull request by darcymeyer**

### CODE REVIEW

**Comment by milesmcc** [comment]
Perhaps `&mdash;`? `&dash;` is not a valid [HTML entity](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references).

**Comment by darcymeyer** [comment]
On Firefox `&dash;` displayed a dash. I'll update it.

**Comment by nzufelt** [comment]
Love it!  We don't want no 👹 `mash`

**Comment by milesmcc** [comment]
Graveyard _smash_!

**Pull request merged**
