### PR TITLE
Adding Alex's essay

### PR DESCRIPTION
**Pull request by Reichenbachian**
Not sure if we have a defined format to add these essays in, so I went with what was most sensical.

### CODE REVIEW

**Comment by Reichenbachian** [comment]
I firmly believe that education is enhanced by flaming text.

**Comment by milesmcc** [comment]
I'm not sure if flaming text exudes professionalism. Because other people—educators and students alike—might use this site once our course concludes, we should be mindful of our image.

**Comment by Reichenbachian** [comment]
The former is a matter of debate! And the ladder is a test of our new pull request master's judgement.

**Comment by ruddfawcett** [comment]
Hey! Closing this for now due to the sheer quantity of open PRs and the potential for many, many merge conflicts. Please reopen a new pull request once the contributing guidelines have been updated!

**Pull request closed without merging**
