### PR TITLE
Added some initial styling to website

### PR DESCRIPTION
**Pull request by ruddfawcett**
This PR seeks to add some initial styling to the existing HTML (though it was a bit restructured).

I recognize that I should have been committing more frequently throughout this rebuild, but that is something that I need to work on doing. 

Also, GitHub is telling me that this can't be automatically merged, so I'll check out why that is.

You can check out this [redesign live here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/ruddfawcett/open_source_movement_csc630/fawcett_redesign/index.html).

### CODE REVIEW

**Comment by ruddfawcett** [comment]
Just resolved some conflicts, so this should now merge into master with no issues.

**Comment by milesmcc** [comment]
I love the look of the site. If we decide to take the pure-HTML route (as opposed to Jekyll), I think this PR is the way to go.

I noticed on the `Resources` page there wasn't a `Made with <3 at Phillips Academy` footer (see image below), but apart from that this PR has a 👍 from me!

screen shot 2017-12-10 at 4 48 56 pm

**Comment by milesmcc** [comment]
This looks great, but I wonder if it could be improved by increasing the contrast of the header text? It's a bit difficult to read right now.

**Comment by ruddfawcett** [comment]
@milesmcc yeah I have that locally. I’ll push when I get a chance.

**Comment by ruddfawcett** [comment]
@nzufelt Should I continue working on this in order to keep up with conflicts in master? Or should I let it be for now?

**Comment by nzufelt** [comment]
Great question!  I think I'll put the two "routes" (jekyll vs raw html) to a vote when we get back.  That will settle things, and we can move forward with one option.

**Comment by ruddfawcett** [comment]
@nzufelt Should I begin cherrypicking changes from other pull requests to merge into this one? Or how should we proceed?

**Comment by ruddfawcett** [comment]
@milesmcc bumped the contrast in header 👍 .

**Comment by nzufelt** [comment]
This has some conflicts with `assignments.html` and `git.html`.  I won't be changing those any time soon... can someone update those?

**Comment by ruddfawcett** [comment]
On it.

**Comment by nzufelt** [comment]
Well, I accepted some other PRs and now we have even more conflicts.  I'll investigate.

**Pull request merged**
