### PR TITLE
Update contribution guidelines according to Contributor Covenant

### PR DESCRIPTION
**Pull request by milesmcc**
Populate the contribution guidelines with [Contributor Covenant](http://contributor-covenant.org)

### CODE REVIEW

**Comment by ruddfawcett** [comment]
Perhaps this is something that could be referenced in a `CODE_OF_CONDUCT.md` file à la [Atom](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) or [Rails](https://github.com/rails/rails/blob/master/CODE_OF_CONDUCT.md) (though the Rails page has been moved to an external page)? I feel that `CONTRIBUTING.md` should be more for specific pull request guidelines for this particular repository. For example, does your code follow a prescribed style? Some examples along these lines are [CocoaPods](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) or [react-native](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md). 

What do you think?

**Comment by milesmcc** [comment]
I agree that `CONTRIBUTING.md` is somewhat ambiguous in purpose. What if we created two files that served these two different purposes:

- **`CODE_OF_CONDUCT.md`** or `CONTRIBUTING.md` that defines the code of conduct for contributing
- **`CONTRIBUTION_GUIDELINES.md`** or `CONTRIBUTING.md` that defines style guidelines and general requirements for pull requests.

Some examples of this model exist [here](https://github.com/frappe/bench/blob/master/docs/contribution_guidelines.md) and [here](https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/contribution-guidelines.md).

Thoughts on this refactoring?

**Comment by ruddfawcett** [comment]
Definitely. Just because GitHub automatically recognizes a `CONTRIBUTING.md` file for every new pull request (if one is included in the root of a repository), I think that there should be a file by that name outlining specific contribution guidelines.

Additionally, we can have a `CODE_OF_CONDUCT.md` file that references the Contributor Covenant and is mentioned in `CONTRIBUTING.md`.

**Comment by nzufelt** [comment]
The idea you two landed on sounds good to me.  @milesmcc can you make that change for this PR?  And add the appropriate reference to [resources/resources.md](https://github.com/nzufelt/open_source_movement_csc630/blob/master/resources/resources.md) (for example, the Contributor Covenant post).

**Comment by milesmcc** [comment]
I've split the previously dual-purpose `CONTRIBUTING.md` into separate files, `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md`. (See 52288a4.) 

I think @ruddfawcett is right that the contribution guideline file should be named `CONTRIBUTING.md`, especially considering that GitHub recognizes this file when PRs are created.

I've also added a CONTRIBUTING.md and CODE_OF_CONDUCT.md links to Rails' equivalents in `resources.md`. (See 54bc77f.)

Is this what you were thinking @nzufelt and @ruddfawcett?

**Comment by nzufelt** [comment]
Made a final cleanup, looks good now.  Thanks y'all!

**Pull request merged**
