### PR TITLE
Fixed typo in README

### PR DESCRIPTION
**Pull request by malcolmessaid**
Publicly was spelled "publically' in the README.

### CODE REVIEW

**Comment by nzufelt** [comment]
Ha!  Thanks.

**Comment by nzufelt** [comment]
Oh, but you have 313 files changed, because you forked from @nicholas-miklaucic's version of the repo.  You'll need to make sure you're up to date with this fork before you submit a PR (create a new branch locally, pull down this fork's master branch, make your changes, push to a new branch on your repository, submit a PR from that branch).

**Comment by kabirnagral** [comment]
I resolved this PR on a separate branch in #59.

**Comment by ruddfawcett** [comment]
Closing due to @kabirnagral's branch.

**Pull request closed without merging**
